server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb://root:password@localhost:27017/usuarios?authSource=admin

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
